### PR TITLE
make the lib a little better

### PR DESCRIPTION
**Pull request by itslukej**

### CODE REVIEW

**Comment by Phxntxm** [comment]
A+

**Comment by developerCodex** [comment]
This is from the discord.py.

**Comment by Hackzzila** [comment]
It is from disco

**Comment by JoeBanks13** [comment]
Umm isn't this disco-py

**Comment by JoeBanks13** [comment]
Or some other lib

**Comment by fwrs** [comment]
no it's christian python library,,

**Comment by JoeBanks13** [comment]
ok

**Pull request closed without merging**
